version: '3'
services:
  server:
    build:
      context: ./api-server/
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - 5000:5000
  client:
    build:
      context: ./api-client/
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    depends_on:
      - "server"